name: Cypress Tests with Allure Report

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install project dependencies
      - name: Install dependencies
        run: npm install

      # Install Allure command-line tool
      - name: Install Allure command-line
        run: npm install -g allure-commandline

      # Ensure results directory exists
      - name: Ensure results directory exists
        run: mkdir -p cypress/results

      # Run Cypress tests with Allure integration
      - name: Run Cypress tests with Allure
        run: npx cypress run --env allure=true

      # Generate Allure report
      - name: Generate Allure report
        if: always()
        run: allure generate allure-results --clean -o allure-report

      # Upload Allure report as an artifact
      - name: Upload Allure report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report
          retention-days: 30

      # Upload test results as an artifact
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-results
          path: cypress/results
          retention-days: 30
